### ISSUE TITLE
fissix.pgen2.parse.ParseError: bad input: type=1, value='print', context=(' ', (211, 14))

### ISSUE THREAD

**Issue by gregory-carlton** [majwilson/python-to-javascript#6]
Hello. I am running your code as you state
`python3 PythonToJavascript  \
    --in_file /home/user/Documents/repos/python-to-javascript/decode.py \
    --out_dir /home/user/Documents/repos/python-to-javascript/`

And I am getting the error in the title. Please assist. Python3.10

![Screenshot 2022-09-22 213954](https://user-images.githubusercontent.com/93105136/191882759-3d177c71-7f57-4952-a75b-6c4378e2f0ed.png)

**Comment by ericmarceau-rogers** [comment]
Hello, I seem to be getting the same errors with my attempt to use the code with 

- Ubuntu **22.04.5** LTS 64-bit
- Kernel Linux **6.8.0-45-generic** x86_64
- MATE **1.26.0**
- Python **3.10.12**

```
/DB001_F4/WORK ./
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/DB001_F4/WORK/python-to-javascript-master/PythonToJavascript/__main__.py", line 63, in <module>
    main()
  File "/home/ericthered/.local/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ericthered/.local/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ericthered/.local/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ericthered/.local/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/DB001_F4/WORK/python-to-javascript-master/PythonToJavascript/__main__.py", line 23, in main
    parsed = parseString( source )
  File "/DB001_F4/WORK/python-to-javascript-master/PythonToJavascript/helpers.py", line 22, in parseString
    return driver.parse_string( dedent( string ) + "\n\n", debug=True )
  File "/home/ericthered/.local/lib/python3.10/site-packages/fissix/pgen2/driver.py", line 102, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/home/ericthered/.local/lib/python3.10/site-packages/fissix/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/home/ericthered/.local/lib/python3.10/site-packages/fissix/pgen2/parse.py", line 164, in addtoken
    raise ParseError("bad input", type, value, context)
fissix.pgen2.parse.ParseError: bad input: type=1, value='pattern', context=(' ', (383, 10))
```
Note:  RC = 1


So, I tried all your diagnostic test files, and the results are as follows:

```
 ################################################################################
 FILE: attr_test.py

SYSPATH ['/DB001_F4/WORK/python-to-javascript-master/PythonToJavascriptForTests', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/ericthered/.local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/DB001_F4/WORK/python-to-javascript-master', '/DB001_F4/WORK/python-to-javascript-master/PythonToJavascript']
/DB001_F4/WORK/python-to-javascript-master/test-e2e/python/attr_test.py ./

CLASS  TObj
----METHOD  __init__

CLASS  AttrTests
----METHOD  test_getAttr
----METHOD  test_setAttr
----METHOD  test_hasAttr
FUNCTION   makeTObj
RC = 0

 ################################################################################


 Hit return to continue ...

 ################################################################################
 FILE: dict_comprehension_test.py

SYSPATH ['/DB001_F4/WORK/python-to-javascript-master/PythonToJavascriptForTests', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/ericthered/.local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/DB001_F4/WORK/python-to-javascript-master', '/DB001_F4/WORK/python-to-javascript-master/PythonToJavascript']
/DB001_F4/WORK/python-to-javascript-master/test-e2e/python/dict_comprehension_test.py ./

CLASS  DictComprehensionTests
----METHOD  test_dictComprehension_01
----METHOD  test_dictComprehension_02
----METHOD  test_dictComprehension_03
RC = 0

 ################################################################################


 Hit return to continue ...

 ################################################################################
 FILE: list_comprehension_test.py

SYSPATH ['/DB001_F4/WORK/python-to-javascript-master/PythonToJavascriptForTests', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/ericthered/.local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/DB001_F4/WORK/python-to-javascript-master', '/DB001_F4/WORK/python-to-javascript-master/PythonToJavascript']
/DB001_F4/WORK/python-to-javascript-master/test-e2e/python/list_comprehension_test.py ./

CLASS  ListComprehensionTests
----METHOD  test_ListComprehension_01
----METHOD  test_ListComprehension_02
----METHOD  test_ListComprehension_03
----METHOD  test_ListComprehension_04
RC = 0

 ################################################################################


 Hit return to continue ...

 ################################################################################
 FILE: list_slice_test.py

SYSPATH ['/DB001_F4/WORK/python-to-javascript-master/PythonToJavascriptForTests', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/ericthered/.local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/DB001_F4/WORK/python-to-javascript-master', '/DB001_F4/WORK/python-to-javascript-master/PythonToJavascript']
/DB001_F4/WORK/python-to-javascript-master/test-e2e/python/list_slice_test.py ./

CLASS  ListSliceTests
----METHOD  test_ListSlice_01
----METHOD  test_ListSlice_02
----METHOD  test_ListSlice_03
----METHOD  test_ListSlice_04
----METHOD  test_ListSlice_05
FUNCTION   getStrings
RC = 0

 ################################################################################


 Hit return to continue ...

 ################################################################################
 FILE: string_interpolation_test.py

SYSPATH ['/DB001_F4/WORK/python-to-javascript-master/PythonToJavascriptForTests', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/ericthered/.local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/DB001_F4/WORK/python-to-javascript-master', '/DB001_F4/WORK/python-to-javascript-master/PythonToJavascript']
/DB001_F4/WORK/python-to-javascript-master/test-e2e/python/string_interpolation_test.py ./

CLASS  StringInterpolationTests
----METHOD  test_StringInterpolation_01
----METHOD  test_StringInterpolation_02
----METHOD  test_StringInterpolation_03
FUNCTION   getStrings
RC = 0

 ################################################################################


 Hit return to continue ...

 ################################################################################
 FILE: tuple_unpack_test.py

SYSPATH ['/DB001_F4/WORK/python-to-javascript-master/PythonToJavascriptForTests', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/ericthered/.local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/DB001_F4/WORK/python-to-javascript-master', '/DB001_F4/WORK/python-to-javascript-master/PythonToJavascript']
/DB001_F4/WORK/python-to-javascript-master/test-e2e/python/tuple_unpack_test.py ./

CLASS  TupleUnpackTests
----METHOD  test_TupleUnpack_01
----METHOD  test_TupleUnpack_02
----METHOD  test_TupleUnpack_03
FUNCTION   getStrings
RC = 0

 ################################################################################


 Hit return to continue ...

 ################################################################################
 FILE: zip_test.py

SYSPATH ['/DB001_F4/WORK/python-to-javascript-master/PythonToJavascriptForTests', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/ericthered/.local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/DB001_F4/WORK/python-to-javascript-master', '/DB001_F4/WORK/python-to-javascript-master/PythonToJavascript']
/DB001_F4/WORK/python-to-javascript-master/test-e2e/python/zip_test.py ./

CLASS  ZipTests
----METHOD  test_zip
----METHOD  test_zip_differing_lengths
RC = 0

 ################################################################################
```

So ... I can only conclude that the code under the test directory is not identical to the code under the production library.  **I haven't checked that out yet!**

Thank you,
Eric
